force-app/main/default/objects/SobjectPurgeConfiguration__c/SobjectPurgeConfiguration__c.object-meta.xml
<CustomObject>
    <label>SobjectPurgeConfiguration</label>
    <nameField>
        <label>SobjectPurgeConfiguration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SobjectPurgeConfigurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SobjectPurgeConfiguration__c/fields/Child_Relationship_Names__c.field-meta.xml
<CustomField>
    <fullName>Child_Relationship_Names__c</fullName>
    <description>We can add child relationship names to fetch child records</description>
    <label>Child Relationship Names</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SobjectPurgeConfiguration__c/fields/Limit_Query_Rows__c.field-meta.xml
<CustomField>
    <fullName>Limit_Query_Rows__c</fullName>
    <label>Limit Query Rows</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SobjectPurgeConfiguration__c/fields/Schedule_Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Job_Id__c</fullName>
    <label>Schedule Job Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SobjectPurgeConfiguration__c/fields/Schedule_Time__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Time__c</fullName>
    <label>Schedule Time (In Expression)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SobjectPurgeConfiguration__c/fields/SObject_API_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_API_Name__c</fullName>
    <label>SObject API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SobjectPurgeScheduler.cls
/* 
Name : SobjectPurgeScheduler
CreatedDate : 13-OCT-2023
CreatedBy Name : Sachin Gaikwad
Description : Schedule a SobjectPurgeConfiguration__c record based on data from controller
*/

global with sharing class SobjectPurgeScheduler implements Schedulable{
    
    global void execute(SchedulableContext sc){
        string query;
        SobjectPurgeConfiguration__c SobjPurgeConfig;
        SobjPurgeConfig = [Select id,Query__c,Name,Batch_Size__c,Child_Relationship_Names__c,Limit_Query_Rows__c,Schedule_Time__c,SObject_API_Name__c from SobjectPurgeConfiguration__c where Schedule_Job_Id__c =:  sc.getTriggerId() Limit 1];
        if(string.isNotBlank(SobjPurgeConfig.Query__c)){
            query = SobjPurgeConfig.Query__c;
        }
        if(SobjPurgeConfig.Limit_Query_Rows__c != null && SobjPurgeConfig.Limit_Query_Rows__c >0){
            query = query + ' LIMIT '+SobjPurgeConfig.Limit_Query_Rows__c;
        }
        System.debug('query->'+query);

        SobjectPurgeBatchProcessor deleteSobjRecord = new SobjectPurgeBatchProcessor(query,SobjPurgeConfig.id,SobjPurgeConfig.Name,SobjPurgeConfig.Child_Relationship_Names__c);
        		Id batchProcessId = Database.executeBatch(deleteSobjRecord,SobjPurgeConfig.Batch_Size__c.intValue());
                System.debug('batchProcessId-->'+batchProcessId);
    }
}